### ISSUE TITLE
QuPath v0.3.0-rc1

### ISSUE THREAD

**Issue by ap--** [bayer-science-for-a-better-life/qupath-feedstock#9]
please 🥰

**Comment by sdvillal** [comment]
initial commit sent, let's see if it is that easy

are the extensions included in the prebuilt packages we rely on?

I'm curious to see if everything gets to work nicely with JDK16

**Comment by sdvillal** [comment]
first packages are up

minimal testing, so please report any problems

windows built succeeded but upload got stuck, will rerun tomorrow
https://dev.azure.com/sdvillal/feedstock-builds/_build/results?buildId=166&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802

at some point we should setup these pipelines in this org

I deleted most other qupath versions in the channel

**Comment by sdvillal** [comment]
just as a last note, simply re-running the failed windows job has now successfully uploaded the win package
